apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672   # AMQP protocol for communication
              name: amqp-port       # Port name for AMQP protocol
            - containerPort: 15672  # Management UI for RabbitMQ
              name: management-port # Port name for Management UI
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmqa
spec:
  ports:
    - name: amqp-port        # Required name for AMQP port
      port: 5672
      targetPort: 5672
    - name: management-port  # Required name for Management UI port
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP  # Use ClusterIP for internal communication, change to LoadBalancer if external access is required
